steps:
  # install dependencies
  - id: install-dependencies
    name: node
    entrypoint: npm
    args: ['install']
    env: 
    - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'

  # run cypress
  - id: run-cypress
    name: cypress/included:7.0.1
    entrypoint: npx
    args: ['cypress', 'run']
    env: 
    - 'CYPRESS_CACHE_FOLDER=/workspace/.tmp/Cypress'