# This example workflow uses the runner context to set the path to the temporary directory to write logs, 
# and if the workflow fails, it uploads those logs as artifact.
# https://docs.github.com/en/actions/learn-github-actions/contexts

name: Build all actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with logs
        run: |
          mkdir ${{ runner.temp }}/build_logs
          ./build.sh --log-path ${{ runner.temp }}/build_logs
      - name: Upload logs on fail
        if: ${{ success() }} # failure
        uses: actions/upload-artifact@v3
        with:
          name: Build success logs
          path: ${{ runner.temp }}/build_logs