name: Artifacts

on: push # all kind of actions

jobs:
  example-job:
    name: working on artifacts
    runs-on: ubuntu-latest
    steps:

    # The below script generates, uploads and downloads a file named output.log and path is /tmp
      - shell: bash 
        run: |
          expr 1 + 1 > /tmp/output.log

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file # this is the name shows in github. We can download it manually
          path: /tmp/output.log

      - name: Download file # download default location /home/runner/work/CypressWeb_v10_CICD/CypressWeb_v10_CICD
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
          path: some/new/path # path is optional. If didnt mention it will downlaod default location. If mentioned, deafult/some/new/path
      
   
      - name: Download artifact A
        uses: actions/download-artifact@v3
        with:
          name: output-log-file # name of the artifact
          path: ~/some/path/with/a/tilde   # Test downloading an artifact using tilde expansion

     # The below script takes screenshot and uploads
      - name: Checkout
        uses: actions/checkout@v3
      - name: Take screenshot
        if: failure()
        run: |
          ./bin/makeScreenshot /tmp/screen.jpg

      - name: Upload screenshot
        uses: actions/upload-artifact@master # upload our screen shot to GitHub. We can download it from github (dropdown shown at upper right corner)
        # if: failure() # these steps will only run if some previous steps have failed.
        # if: success() && github.ref == 'refs/heads/master' # If it is master branch
        if: failure()
        with:
          name: screen.jpg
          path: /tmp/screen.jpg

      - name: Running cyress scripts
        uses: actions/checkout@v3
      - run: npm ci # same as npm install
      - run: npx cypress run 

    # The below script uploads screenshot and videos from cypress suite
      - name: Upload screenshot
        uses: actions/upload-artifact@master
        if: failure()
        with:
            name: screenshots
            path: cypress/screenshots
        # there might be no screenshots created when:
        # - there are no test failures
        # so only upload screenshots if previous step has failed

    # video should always be generated
      - name: Upload videos
        uses: actions/upload-artifact@master
        if: failure() # success()
        with:
            name: videos
            path: cypress/videos
