name: Chrome browser

on: push

jobs:
  CypressTestChrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Chrome
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          browser: chrome # electron # browser should be present in our system
          # headless: true # headless mode  