name: My Cypress Tests4

on:
  push:
    branches: [ master ] #merge master, 
  pull_request:
    types: [opened]

jobs:
  build:
    name: AllPushes-masterAndAllPRs-opened
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm install