# https://docs.github.com/en/actions/using-workflows/about-workflows
# A matrix strategy lets you use variables in a single job definition to automatically create multiple job runs that are based on the combinations of the variables. 
# For example, you can use a matrix to test your code in multiple operating systems.
# different machines: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
# https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

name: multipleMachineParallel

on: push #all kind of actions

jobs:
  LinuxMachine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  WindowsMachine:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
  
  MacMachine:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
