name: Pull request4

on:
  pull_request:
    branches: [ pr25 ] # runs when a new pr created against existing branch pr25. By default we create pr against master branch
    
jobs:
  build:
    name: AllPRs-master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
