name: My Cy Tests Pull request2

on:
  pull_request:
    branches: [ master ] #new PRs
    
jobs:
  build:
    name: AllPRs-master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        # with:
        #   build: npm install