# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

name: Scheduled job
on:
  schedule:
    - cron:  '10,30,50 * * * *' # Runs every day at 5:42 and 17:42 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Cloning your repository to the runner
      # - name: Build
      #   id: build_step
      #   run: |
      #     ./build
      #     echo "::set-output name=build_id::$BUILD_ID"

  deploy:
    needs: build # runs only when build job completes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: ./deploy --build ${{ needs.build.outputs.build_id }}

  # debug:
  #   needs: [build, deploy]
  #   runs-on: ubuntu-latest
  #   if: ${{ failure() }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: ./debug