# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

name: Scheduled job
on:
  schedule:
    - cron:  '10,40 * * * *' # Runs every day at 5:42 and 17:42 UTC

jobs:
  CronJob:
    runs-on: ubuntu-latest
    # outputs:
    #   build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Cloning your repository to the runner
