name: My Cy Tests variable all actions

on: push
env:
  name: Shaji

jobs:
  usageOfEnvVariable:
    runs-on: ubuntu-latest
    env:
      name: Christo
    steps:
      - run: echo 'Hi ${{ env.name }}'  # Hi Shaji

      - run: echo 'Hi ${{ env.name }}'  # Hi Christo
        env:
          name: Jisto